# Aprendizagem - Homework IV
### II. Programming - Grupo99
(ist1106059, ist1106329)

In [56]:
import numpy as np
from numpy import transpose as T
from numpy.linalg import inv
from math import exp, sqrt
from math import pi as PI


def Normal(x, u, cov, det):
  e = ((-1/2) * (T(x-u) @ inv(cov) @ (x-u))).item()
  N = exp(e) / ((2*PI) * sqrt(det))
  return round(N, 3)


# DADOS
u1 = np.array([[2], [-1]])
cov1 = np.array([[4,1],[1,4]])
det1 = 15
pi1 = 0.5

u2 = np.array([[1],[1]])
cov2 = np.array([[2,0],[0,2]])
det2 = 4
pi2 = 0.5

# OBSERVAÇÔES
x1 = np.array([[1], [0]])
x2 = np.array([[0], [2]])
x3 = np.array([[3], [-1]])



N(x1|u1, cov1) = 0.029

posterior(k=1|x) = 0.015

N(x1|u2, cov2) = 0.062

posterior(k=2|x) = 0.031

P(K=1|x1) = 0.326

P(k=2|x1) = 0.674



In [65]:
### EPOCH 1 ###

# E-STEP

# x1
N1 = Normal(x1, u1, cov1, det1)
print(f"N(x1|u1, cov1) = {N1}")
post11 = round(N1*pi1, 3)
print(f"posterior(k=1|x1) = {post11}")

N2 = Normal(x1, u2, cov2, det2)
print(f"N(x1|u2, cov2) = {N2}")
post21 = round(N2*pi2, 3)
print(f"posterior(k=2|x1) = {post21}")

P11 = round(post11 / (post11 + post21), 3)
print(f"P(K=1|x1) = {P11}")
P21 = round(post21 / (post11 + post21), 3)
print(f"P(k=2|x1) = {P21}")

# x2
print()
N1 = Normal(x2, u1, cov1, det1)
print(f"N(x2|u1, cov1) = {N1}")
post12 = round(N1*pi1, 3)
print(f"posterior(k=1|x2) = {post12}")

N2 = Normal(x2, u2, cov2, det2)
print(f"N(x2|u2, cov2) = {N2}")
post22 = round(N2*pi2, 3)
print(f"posterior(k=2|x2) = {post22}")

P12 = round(post12 / (post12 + post22), 3)
print(f"P(K=1|x2) = {P12}")
P22 = round(post22 / (post12 + post22), 3)
print(f"P(k=2|x2) = {P22}")

# x3
print()
N1 = Normal(x3, u1, cov1, det1)
print(f"N(x3|u1, cov1) = {N1}")
post13 = round(N1*pi1, 3)
print(f"posterior(k=1|x3) = {post13}")

N2 = Normal(x3, u2, cov2, det2)
print(f"N(x3|u2, cov2) = {N2}")
post23 = 0.006
print(f"posterior(k=2|x3) = {post23}")

P13 = round(post13 / (post13 + post23), 3)
print(f"P(K=1|x3) = {P13}")
P23 = round(post23 / (post13 + post23), 3)
print(f"P(k=2|x3) = {P23}")

N(x1|u1, cov1) = 0.029
posterior(k=1|x1) = 0.015
N(x1|u2, cov2) = 0.062
posterior(k=2|x1) = 0.031
P(K=1|x1) = 0.326
P(k=2|x1) = 0.674

N(x2|u1, cov1) = 0.005
posterior(k=1|x2) = 0.003
N(x2|u2, cov2) = 0.048
posterior(k=2|x2) = 0.024
P(K=1|x2) = 0.111
P(k=2|x2) = 0.889

N(x3|u1, cov1) = 0.036
posterior(k=1|x3) = 0.018
N(x3|u2, cov2) = 0.011
posterior(k=2|x3) = 0.006
P(K=1|x3) = 0.75
P(k=2|x3) = 0.25


In [69]:
# M-STEP

# cluster 1
N = P11 + P12 + P13
print(N)
print()
u1 = np.round((P11*x1 + P12*x2 + P13*x3)/N, 3)
print(u1)
print()
cov1 = (P11*((x1-u1) @ T(x1-u1)) + P12*((x2-u1) @ T(x2-u1)) + P13*((x3-u1) @ T(x3-u1)))/N
cov1 = np.round(cov1,3)
print(cov1)
print()
pi1 = round(N/3, 3)
print(pi1)


#cluster 2
N = round(P21 + P22 + P23, 3)
print(N)
print()
u2 = np.round((P21*x1 + P22*x2 + P23*x3)/N, 3)
print(u2)
print()
cov2 = (P21*((x1-u2) @ T(x1-u2)) + P22*((x2-u2) @ T(x2-u2)) + P23*((x3-u2) @ T(x3-u2)))/N
cov2 = np.round(cov2,3)
print(cov2)
print()
pi2 = round(N/3, 3)
print(pi2)

1.187

[[ 2.17 ]
 [-0.445]]

[[ 1.252 -0.93 ]
 [-0.93   0.808]]

0.396
1.813

[[0.785]
 [0.843]]

[[ 0.996 -1.076]
 [-1.076  1.389]]

0.604


In [71]:
### EPOCH 1 ###

# E-STEP

det1 = 0.147
det2 = 0.226

# x1
N1 = Normal(x1, u1, cov1, det1)
print(f"N(x1|u1, cov1) = {N1}")
post11 = round(N1*pi1, 3)
print(f"posterior(k=1|x1) = {post11}")

N2 = Normal(x1, u2, cov2, det2)
print(f"N(x1|u2, cov2) = {N2}")
post21 = round(N2*pi2, 3)
print(f"posterior(k=2|x1) = {post21}")

P11 = round(post11 / (post11 + post21), 3)
print(f"P(K=1|x1) = {P11}")
P21 = round(post21 / (post11 + post21), 3)
print(f"P(k=2|x1) = {P21}")

# x2
print()
N1 = Normal(x2, u1, cov1, det1)
print(f"N(x2|u1, cov1) = {N1}")
post12 = round(N1*pi1, 3)
print(f"posterior(k=1|x2) = {post12}")

N2 = Normal(x2, u2, cov2, det2)
print(f"N(x2|u2, cov2) = {N2}")
post22 = round(N2*pi2, 3)
print(f"posterior(k=2|x2) = {post22}")

P12 = round(post12 / (post12 + post22), 3)
print(f"P(K=1|x2) = {P12}")
P22 = round(post22 / (post12 + post22), 3)
print(f"P(k=2|x2) = {P22}")

# x3
print()
N1 = Normal(x3, u1, cov1, det1)
print(f"N(x3|u1, cov1) = {N1}")
post13 = round(N1*pi1, 3)
print(f"posterior(k=1|x3) = {post13}")

N2 = Normal(x3, u2, cov2, det2)
print(f"N(x3|u2, cov2) = {N2}")
post23 = round(N2*pi2, 3)
print(f"posterior(k=2|x3) = {post23}")

P13 = round(post13 / (post13 + post23), 3)
print(f"P(K=1|x3) = {P13}")
P23 = round(post23 / (post13 + post23), 3)
print(f"P(k=2|x3) = {P23}")

N(x1|u1, cov1) = 0.112
posterior(k=1|x1) = 0.044
N(x1|u2, cov2) = 0.144
posterior(k=2|x1) = 0.087
P(K=1|x1) = 0.336
P(k=2|x1) = 0.664

N(x2|u1, cov1) = 0.003
posterior(k=1|x2) = 0.001
N(x2|u2, cov2) = 0.199
posterior(k=2|x2) = 0.12
P(K=1|x2) = 0.008
P(k=2|x2) = 0.992

N(x3|u1, cov1) = 0.31
posterior(k=1|x3) = 0.123
N(x3|u2, cov2) = 0.015
posterior(k=2|x3) = 0.009
P(K=1|x3) = 0.932
P(k=2|x3) = 0.068


In [72]:
# M-STEP

# cluster 1
N = P11 + P12 + P13
print(N)
print()
u1 = np.round((P11*x1 + P12*x2 + P13*x3)/N, 3)
print(u1)
print()
cov1 = (P11*((x1-u1) @ T(x1-u1)) + P12*((x2-u1) @ T(x2-u1)) + P13*((x3-u1) @ T(x3-u1)))/N
cov1 = np.round(cov1,3)
print(cov1)
print()
pi1 = round(N/3, 3)
print(pi1)


#cluster 2
N = round(P21 + P22 + P23, 3)
print(N)
print()
u2 = np.round((P21*x1 + P22*x2 + P23*x3)/N, 3)
print(u2)
print()
cov2 = (P21*((x1-u2) @ T(x1-u2)) + P22*((x2-u2) @ T(x2-u2)) + P23*((x3-u2) @ T(x3-u2)))/N
cov2 = np.round(cov2,3)
print(cov2)
print()
pi2 = round(N/3, 3)
print(pi2)

1.276

[[ 2.455]
 [-0.718]]

[[ 0.812 -0.429]
 [-0.429  0.24 ]]

0.425
1.724

[[0.503]
 [1.111]]

[[ 0.487 -0.678]
 [-0.678  1.106]]

0.575


In [76]:
# 2

det1 = 0.011
det2 = 0.079

# x1
N1 = Normal(x1, u1, cov1, det1)
print(f"N(x1|u1, cov1) = {N1}")
post11 = round(N1*pi1, 3)
print(f"posterior(k=1|x1) = {post11}")

N2 = Normal(x1, u2, cov2, det2)
print(f"N(x1|u2, cov2) = {N2}")
post21 = round(N2*pi2, 3)
print(f"posterior(k=2|x1) = {post21}")

# x2
print()
N1 = Normal(x2, u1, cov1, det1)
print(f"N(x2|u1, cov1) = {N1}")
post12 = round(N1*pi1, 3)
print(f"posterior(k=1|x2) = {post12}")

N2 = Normal(x2, u2, cov2, det2)
print(f"N(x2|u2, cov2) = {N2}")
post22 = round(N2*pi2, 3)
print(f"posterior(k=2|x2) = {post22}")

# x3
print()
N1 = Normal(x3, u1, cov1, det1)
print(f"N(x3|u1, cov1) = {N1}")
post13 = round(N1*pi1, 3)
print(f"posterior(k=1|x3) = {post13}")

N2 = Normal(x3, u2, cov2, det2)
print(f"N(x3|u2, cov2) = {N2}")
post23 = round(N2*pi2, 3)
print(f"posterior(k=2|x3) = {post23}")



N(x1|u1, cov1) = 0.374
posterior(k=1|x1) = 0.159
N(x1|u2, cov2) = 0.256
posterior(k=2|x1) = 0.147

N(x2|u1, cov1) = 0.0
posterior(k=1|x2) = 0.0
N(x2|u2, cov2) = 0.391
posterior(k=2|x2) = 0.225

N(x3|u1, cov1) = 1.262
posterior(k=1|x3) = 0.536
N(x3|u2, cov2) = 0.0
posterior(k=2|x3) = 0.0
